'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { CONTRATO_TEXTO } from '@/content/contrato';
import { Button } from '@/components/ui/button';
import {
  ContractOtpPanel,
  type ContractOtpPanelHandle,
} from './contract-otp-panel';
import { RequestContractOtpUseCase } from '@/domain/contract/request-contract-otp.use-case';
import { VerifyContractOtpUseCase } from '@/domain/contract/verify-contract-otp.use-case';
import { ResendContractOtpUseCase } from '@/domain/contract/resend-contract-otp.use-case';
import { ValidationError } from '@/lib/validation-error';
import { FeatureDisabledError } from '@/lib/feature-disabled-error';

/**
 * OTP flow state machine — captures every observable transition inside the
 * contract step so the UI can react predictably:
 *
 *   idle         → initial state, before any OTP call
 *   sending      → POST /v1/otp/contract/request in flight (initial send)
 *   sent         → SMS sent, awaiting user input
 *   verifying    → POST /v1/otp/contract/verify in flight
 *   verified     → terminal success; `onVerified()` + `onNext()` fired
 *   error        → last verify failed (errorMessage populated)
 *   resending    → POST /v1/otp/contract/resend in flight (user clicked
 *                  "Reenviar código" after cooldown)
 */
export type StepContratoOtpPhase =
  | 'idle'
  | 'sending'
  | 'sent'
  | 'verifying'
  | 'verified'
  | 'error'
  | 'resending';

export interface StepContratoProps {
  accepted: boolean;
  onAcceptedChange: (value: boolean) => void;
  onNext: () => void;
  onBack: () => void;
  /**
   * Toggle for the OTP overlay. When `true`, the "Avançar" click triggers
   * `POST /v1/otp/contract/request` and renders `ContractOtpPanel`; only
   * after a successful verify is `onNext()` called. When `false` (default)
   * the legacy flow applies: "Avançar" calls `onNext()` directly.
   */
  otpEnabled?: boolean;
  /**
   * E.164 BR phone of the tutor. Forwarded to the OTP endpoints. Required
   * when `otpEnabled=true`. Ignored otherwise. PII — never displayed; only
   * the server-built `phoneMasked` is rendered.
   */
  phone?: string;
  /**
   * Per-session correlation UUID generated by the parent. When `null` on
   * mount and the user clicks "Avançar" with `otpEnabled=true`, a new UUID
   * v4 is generated locally and propagated up via
   * `onContractAttemptIdAssigned`.
   */
  contractAttemptId?: string | null;
  onContractAttemptIdAssigned?: (id: string) => void;
  /**
   * Invoked with the opaque `verificationToken` returned by the verify
   * endpoint on success. The parent stores the token in state and
   * forwards it to `POST /v1/register/contract` later.
   */
  onVerified?: (verificationToken: string) => void;
}

const COOLDOWN_FALLBACK_SECONDS = 60;

export function StepContrato({
  accepted,
  onAcceptedChange,
  onNext,
  onBack,
  otpEnabled = false,
  phone,
  contractAttemptId = null,
  onContractAttemptIdAssigned,
  onVerified,
}: StepContratoProps) {
  const checkboxId = 'contrato-aceite';

  const [otpPhase, setOtpPhase] = useState<StepContratoOtpPhase>('idle');
  const [phoneMasked, setPhoneMasked] = useState<string>('');
  const [cooldownSeconds, setCooldownSeconds] = useState<number>(0);
  const [errorMessage, setErrorMessage] = useState<string | undefined>(
    undefined,
  );
  const panelRef = useRef<ContractOtpPanelHandle>(null);
  /**
   * Internal mirror of `contractAttemptId`. We can't rely on the prop being
   * updated synchronously by the parent after `onContractAttemptIdAssigned`
   * fires — React batches state updates, so the next click would still see
   * `contractAttemptId === null`. Storing the ID in a ref lets `verify` /
   * `resend` continue with the same correlation ID without waiting for the
   * parent to re-render.
   */
  const attemptIdRef = useRef<string | null>(contractAttemptId);
  useEffect(() => {
    if (contractAttemptId && attemptIdRef.current !== contractAttemptId) {
      attemptIdRef.current = contractAttemptId;
    }
  }, [contractAttemptId]);

  // ---- Cooldown tick (1Hz) -------------------------------------------------
  useEffect(() => {
    if (cooldownSeconds <= 0) return;
    const id = window.setInterval(() => {
      setCooldownSeconds((s) => (s > 0 ? s - 1 : 0));
    }, 1000);
    return () => {
      window.clearInterval(id);
    };
  }, [cooldownSeconds]);

  // ---- Stable use-case instances (avoid recreating per render) ------------
  const requestUseCase = useRef(new RequestContractOtpUseCase());
  const verifyUseCase = useRef(new VerifyContractOtpUseCase());
  const resendUseCase = useRef(new ResendContractOtpUseCase());

  // -------------------------------------------------------------------------
  // Click on "Avançar"
  // -------------------------------------------------------------------------
  const handleAdvanceClick = useCallback(async (): Promise<void> => {
    if (!accepted) return;

    if (!otpEnabled) {
      // Legacy behaviour — unchanged. The parent moves to the payment step.
      onNext();
      return;
    }

    // OTP-enabled path: require phone + handlers. If anything critical is
    // missing the safest fallback is the legacy `onNext()` so we never
    // strand the funnel on a misconfigured deployment.
    if (!phone || !onContractAttemptIdAssigned || !onVerified) {
      onNext();
      return;
    }

    // Generate the attempt ID once per session (if the parent has not yet)
    let attemptId = attemptIdRef.current ?? contractAttemptId ?? null;
    if (!attemptId) {
      attemptId = crypto.randomUUID();
      attemptIdRef.current = attemptId;
      onContractAttemptIdAssigned(attemptId);
    }

    setErrorMessage(undefined);
    setOtpPhase('sending');
    try {
      const result = await requestUseCase.current.execute({
        contractAttemptId: attemptId,
        phone,
      });
      setPhoneMasked(result.phoneMasked);
      setCooldownSeconds(result.cooldownSeconds || COOLDOWN_FALLBACK_SECONDS);
      setOtpPhase('sent');
    } catch (err) {
      if (err instanceof FeatureDisabledError) {
        // Defensive: the feature was toggled off between mount and click.
        // Silently fall back to the legacy flow instead of stranding the
        // user on an error message.
        // eslint-disable-next-line no-console
        console.warn('OTP feature disabled — falling back to legacy flow');
        onNext();
        return;
      }
      if (err instanceof ValidationError) {
        setErrorMessage(
          err.fieldErrors._form ?? 'Erro de conexão. Tente novamente.',
        );
      } else {
        setErrorMessage('Erro de conexão. Tente novamente.');
      }
      setOtpPhase('error');
    }
  }, [
    accepted,
    contractAttemptId,
    onContractAttemptIdAssigned,
    onNext,
    onVerified,
    otpEnabled,
    phone,
  ]);

  // -------------------------------------------------------------------------
  // ContractOtpPanel.onSubmit (verify)
  // -------------------------------------------------------------------------
  const handleOtpSubmit = useCallback(
    async (code: string): Promise<void> => {
      const attemptId = attemptIdRef.current ?? contractAttemptId;
      if (!attemptId || !onVerified) return;
      setErrorMessage(undefined);
      setOtpPhase('verifying');
      try {
        const result = await verifyUseCase.current.execute({
          contractAttemptId: attemptId,
          code,
        });
        setOtpPhase('verified');
        onVerified(result.verificationToken);
        onNext();
      } catch (err) {
        if (err instanceof FeatureDisabledError) {
          // eslint-disable-next-line no-console
          console.warn('OTP feature disabled — falling back to legacy flow');
          onNext();
          return;
        }
        if (err instanceof ValidationError) {
          setErrorMessage(
            err.fieldErrors._form ?? 'Erro de conexão. Tente novamente.',
          );
        } else {
          setErrorMessage('Erro de conexão. Tente novamente.');
        }
        // Stay in "sent" so the user can edit/retry; flag as `error` to
        // surface the message under the input.
        setOtpPhase('error');
      }
    },
    [contractAttemptId, onNext, onVerified],
  );

  // -------------------------------------------------------------------------
  // ContractOtpPanel.onResend
  // -------------------------------------------------------------------------
  const handleOtpResend = useCallback(async (): Promise<void> => {
    const attemptId = attemptIdRef.current ?? contractAttemptId;
    if (!attemptId || !phone) return;
    setErrorMessage(undefined);
    setOtpPhase('resending');
    try {
      const result = await resendUseCase.current.execute({
        contractAttemptId: attemptId,
        phone,
      });
      setPhoneMasked(result.phoneMasked);
      setCooldownSeconds(result.cooldownSeconds || COOLDOWN_FALLBACK_SECONDS);
      setOtpPhase('sent');
      panelRef.current?.clear();
    } catch (err) {
      if (err instanceof FeatureDisabledError) {
        // eslint-disable-next-line no-console
        console.warn('OTP feature disabled — falling back to legacy flow');
        onNext();
        return;
      }
      if (err instanceof ValidationError) {
        setErrorMessage(
          err.fieldErrors._form ?? 'Erro de conexão. Tente novamente.',
        );
      } else {
        setErrorMessage('Erro de conexão. Tente novamente.');
      }
      setOtpPhase('error');
    }
  }, [contractAttemptId, onNext, phone]);

  const isAdvancing =
    otpPhase === 'sending' || otpPhase === 'verifying' || otpPhase === 'resending';

  const showOtpPanel =
    otpEnabled &&
    (otpPhase === 'sent' ||
      otpPhase === 'verifying' ||
      otpPhase === 'error' ||
      otpPhase === 'resending');

  return (
    <div className="space-y-6">
      {/* Contract text with fixed-height scrollable area */}
      <div
        className="rounded-lg border border-border bg-muted/30 p-4 overflow-y-auto whitespace-pre-wrap text-sm leading-relaxed text-foreground"
        style={{ height: '200px' }}
        role="region"
        aria-label="Texto do contrato"
        tabIndex={0}
      >
        {CONTRATO_TEXTO}
      </div>

      {/* Acceptance checkbox */}
      <div className="flex items-start gap-3">
        <input
          id={checkboxId}
          type="checkbox"
          checked={accepted}
          onChange={(e) => onAcceptedChange(e.target.checked)}
          disabled={showOtpPanel}
          className="mt-0.5 h-4 w-4 cursor-pointer rounded border-border accent-[#4E8C75]"
        />
        <label
          htmlFor={checkboxId}
          className="text-sm leading-snug cursor-pointer select-none"
        >
          Li e concordo com todos os termos e condições do Contrato de Prestação de Serviços do
          Plano Emergência Veterinária.
        </label>
      </div>

      {/* OTP overlay — only when flag is on and a request was issued */}
      {showOtpPanel ? (
        <ContractOtpPanel
          ref={panelRef}
          phoneMasked={phoneMasked}
          cooldownSeconds={cooldownSeconds}
          onSubmit={handleOtpSubmit}
          onResend={handleOtpResend}
          errorMessage={errorMessage}
          busy={otpPhase === 'verifying' || otpPhase === 'resending'}
        />
      ) : null}

      {/* When OTP error occurs before the panel was rendered (i.e. the
          initial request failed), show the message above navigation. */}
      {!showOtpPanel && otpPhase === 'error' && errorMessage ? (
        <p
          role="alert"
          aria-live="assertive"
          className="text-sm text-destructive"
        >
          {errorMessage}
        </p>
      ) : null}

      {/* Navigation */}
      <div className="flex gap-3 pt-2">
        <Button
          type="button"
          variant="outline"
          onClick={onBack}
          disabled={isAdvancing}
          className="flex-1"
        >
          Voltar
        </Button>
        <Button
          type="button"
          onClick={handleAdvanceClick}
          disabled={!accepted || isAdvancing || showOtpPanel}
          className="flex-1 bg-[#4E8C75] hover:bg-[#3d7260] text-white"
        >
          {otpPhase === 'sending' ? 'Enviando código…' : 'Avançar'}
        </Button>
      </div>
    </div>
  );
}
